### ISSUE TITLE
Include Sanitized Capabilities with Suite Title

### ISSUE THREAD

**Issue by fijijavis** [fijijavis/wdio-mochawesome-reporter#10]
When running tests against multiple browsers it is impossible to determine which result in the mochawesome report goes to which browser execution.

Add option to include sanitized capabilities with the suite title

**Comment by mherodev** [comment]
Can't wait for this, esp. with Allure giving me essentially the same if not worse issues.

**Comment by fijijavis** [comment]
@mherodev v1.1.1 has been released.  This will append the WDIO sanitizedCapabilities to the end of the suite name.
