### ISSUE TITLE
Missing browser in report

### ISSUE THREAD

**Issue by mherodev** [fijijavis/wdio-mochawesome-reporter#11]
I'm not certain if this is an issue that requires downstream updates, but looking at the generated `.json` file, there is no mention of the browser a test-file was run in. This makes the generated reports a little useless when run across multiple browsers.

**Comment by fijijavis** [comment]
@mherodev I noticed that too.  Looks like I lost some code when I converted this to a public project.  #10 was logged to fix the issue.  I hope to have an update out tomorrow.  I’m going to close this one.
