### ISSUE TITLE
npm documentation doesn't match github

### ISSUE THREAD

**Issue by mherodev** [fijijavis/wdio-mochawesome-reporter#12]
I made the mistake of using `npm install --save mochawesome-report-generator` instead of `npm install --save-dev mochawesome-report-generator@2.3.2` which causes issues due to v3. Just need a fresh publish with an updated version, I imagine.

**Comment by fijijavis** [comment]
@mherodev Release v1.1.1 included publishing the correct documentation to NPM.  Compatibility with v3 of ```mochawesome-report-generator``` is going to take some time to investigate.  For now you can remove the package and install a specific version.  See #8 for details.
