### ISSUE TITLE
License

### ISSUE THREAD

**Issue by sfbwalder** [fijijavis/wdio-mochawesome-reporter#14]
We would appreciate if you could publish an open source license for this project.  We work at a corporation where the open source we use needs to be licensed.

Thanks, Ben

**Comment by fijijavis** [comment]
@sfbwalder Sure thing.  Probably get to it tomorrow morning

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fijijavis** [comment]
@sfbwalder published v 1.1.2 with MIT license
