### ISSUE TITLE
Error generating mochawesome html report

### ISSUE THREAD

**Issue by biz786** [fijijavis/wdio-mochawesome-reporter#23]
Hi i am having an issue generating html report using the wdio-mochawesome-reporter. The JSON file is generated fine but when i run the line below in my package.config -
 "generateMochawesome":"marge <path/to/results.json> --reportTitle 'My Project Results'" ; 

i get an error as show in the image attached.
## Environment
Typescript,nodejs,mocha,webdriverio

* WebdriverIO version:
* Node.js version: 6.0.0
* wdio testrunner - running synchronous tests:
* Additional wdio packages used (if applicable): 
services:['chromedriver']
reporters:['spec','mochawesome']
   reporterOptions:{
   outputDir: './'
}

**Comment by biz786** [comment]
![package json](https://user-images.githubusercontent.com/4602480/36999438-1537c85c-208e-11e8-9eeb-7b87c73e8dc1.jpg)

**Comment by biz786** [comment]
![error_mochawesome-reporter_webdriverio](https://user-images.githubusercontent.com/4602480/36999450-21774c50-208e-11e8-96e9-78fb8541a53a.jpg)

**Comment by samwarwick** [comment]
I experienced the same problem using wdio-mochawesome-reporter 1.3.0 and mochawesome-report-generator 3.1.1. I was able to get the report working by downgrading mochawesome-report-generator to 2.3.2.

**Comment by fijijavis** [comment]
Yes...this is actually documented in the README.  There is an open PR to get 2.x and 3.x versions supported.

**Comment by biz786** [comment]
@fijijavis I did not see it in the readme. Could u point me to the link please.

**Comment by fijijavis** [comment]
I apparently can’t link to the line from my phone but it is in the Mochawesome Report Generator section directly under the sample npm install

**Comment by biz786** [comment]
That fixed it thanks a lot @samwarwick @fijijavis . But i have another error now :-(. I am trying to add a msg(addContext) to the report as i want to send some "text" when the mocha test passes. But i get error 

ERROR: Cannot find module 'mochawesome/addContext'

Its a typescript project so am i importing it incorrectly? or is "addContext" not supported for typescript?

**Comment by samwarwick** [comment]
My bad too @fijijavis - the readme does clearly state to use the 2.3.2 and that 3.x is not compatible.
https://github.com/fijijavis/wdio-mochawesome-reporter
