### ISSUE TITLE
Unable to AddContext to Mochawesome Report

### ISSUE THREAD

**Issue by biz786** [fijijavis/wdio-mochawesome-reporter#24]
Hi im trying to addContext to the mochawesome reporter in a typescript+nodejs project.I can generate json and html file.

But i am unable to resolve the import....get ERROR: 
**Cannot find module 'mochawesome/addContext'**

## Environment
Typescript,nodejs,mocha,webdriverio

* WebdriverIO version:
* Node.js version: 6.0.0
* wdio testrunner - running synchronous tests:
* Additional wdio packages used (if applicable): 
services:['chromedriver']
reporters:['spec','mochawesome']
   reporterOptions:{
   outputDir: './'
}

**Comment by biz786** [comment]
![package json](https://user-images.githubusercontent.com/4602480/37011198-08b54a12-20bd-11e8-94e3-267519cd300f.jpg)

**Comment by biz786** [comment]
<img width="772" alt="error" src="https://user-images.githubusercontent.com/4602480/37012693-f33bdf00-20c3-11e8-858a-aa066c5266aa.PNG">

**Comment by biz786** [comment]
![mocha_test](https://user-images.githubusercontent.com/4602480/37012759-3e8628a8-20c4-11e8-9d31-955d20a82d42.jpg)

**Comment by biz786** [comment]
<img width="313" alt="tsconfig" src="https://user-images.githubusercontent.com/4602480/37012765-44c918c4-20c4-11e8-9537-f55eea9161e0.PNG">

**Comment by biz786** [comment]
<img width="343" alt="pacjagejson" src="https://user-images.githubusercontent.com/4602480/37012825-9a6824b4-20c4-11e8-819c-7d4707c9d673.PNG">

**Comment by biz786** [comment]
@fijijavis any idea/help would be appreciated

**Comment by fijijavis** [comment]
@biz786 looks like you don’t have the mochawesome package in your package.json.  If you npm install it you should be good.  I have an issue to add mochawesome-report-generator as a peer dependency.  Guess I probably need to add this one to it too

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by biz786** [comment]
@fijijavis  yupp that was it ! Thanks a lot!
