### ISSUE TITLE
Version Compatibility issue with latest  wdio-mocha-framework 0.5.12

### ISSUE THREAD

**Issue by madhushesharam** [fijijavis/wdio-mochawesome-reporter#27]
npm install --save wdio-mochawesome-reporter-1.3.0.tgz

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "wdio-mochawesome-reporter-1.3.0.tgz"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6

npm ERR! No compatible version found: wdio-mocha-framework@~0.5.12
npm ERR! Valid install targets:
npm ERR! 0.5.8, 0.4.0
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by fijijavis** [comment]
If this is still a problem please enter a new issue
