### ISSUE TITLE
adding screenshots

### ISSUE THREAD

**Issue by snoblenet** [fijijavis/wdio-mochawesome-reporter#3]
Hi there,
Nice job.
Would you expect the following to work?
```
exports.config = {
  afterEach: () => {
    addContext(this, browser.saveScreenshot());
  },
}
```
As screenshots are not currently being saved to my report.

Thanks,

Steven

**Comment by fijijavis** [comment]
@snoblenet Thanks for the feedback.  

I'm actually working on a solution now but forgot to log the issue.  

I had a hacky solution working for adding screenshots but didn't want to pull that into the public repo.

**Comment by snoblenet** [comment]
Thanks. Did you have an ETA? So I can advise my team whether I should roll a ticket over into the next sprint.

**Comment by snoblenet** [comment]
I think the issue is with `addContext` rather than `browser.saveScreenshot()` as I can't add a string as context either.

**Comment by fijijavis** [comment]
I agree. addContext is a mocha specific thing which I think isn’t getting passed through to wdio.  That’s what I’ll be investigating.  As far as ETA I should have pretty much all day Friday to investigate so hopefully some time next week there will be a new release.

**Comment by snoblenet** [comment]
Hi Jim -- any updates? Cheers.

**Comment by fijijavis** [comment]
@snoblenet On Friday I played around with the ```addContext``` and found that no matter what I did the added context was not exposed to the WDIO BaseReporter (utilized by all custom reporters).  So I think an exact port of the ```addContext``` functionality provided by Mochawesome is probably going to take a change to WDIO.

Good News is I did find that the WDIO BaseReporter does have a record of all screenshots captured for a given test.  So I'm going to address adding screenshots in this issue then create a separate issue for figuring out how to implement the ```addContext``` functionality.  Should have something ready in the next couple days.

**Comment by snoblenet** [comment]
Thanks. I'll check out `3-Add-Context-Feature` to see if I can contribute.

**Comment by fijijavis** [comment]
I have a good solution.  For some reason all the tests started failing yesterday (even in master).  Working through those issues then should be able to push a release.

**Comment by fijijavis** [comment]
Released a new version this morning
