### ISSUE TITLE
Images and urls are not rendered in HTML Report correctly when provided in testContext

### ISSUE THREAD

**Issue by qaiser110** [fijijavis/wdio-mochawesome-reporter#30]
I have the following test in wdio:

```
describe('Test Report', function() {

  it('should display link and image', function() {
    addContext(this, 'http://webdriver.io/');
    addContext(this, 'http://webdriver.io/images/webdriverio.png');
  });
```

I expect to see a link and an image in the report, but I see this instead:

![image](https://user-images.githubusercontent.com/2253847/44463182-49c95980-a65a-11e8-8450-1ba8d5b07b3f.png)

I've created a PR for this fix: #29 

I'm unable to run the tests, and the build is breaking because some tests would need to be fixed for this PR to merge. Is there a guide to running the tests, or can somebody help me with this merge.

**Comment by fijijavis** [comment]
This should be resolved in the most recent release.  If not please submit a new issue with steps to reproduce
