### ISSUE TITLE
Output filename

### ISSUE THREAD

**Issue by ziglef** [fijijavis/wdio-mochawesome-reporter#34]
Hey, first of all thank you for all the effort into this project!

I was trying to customize the output of the reporter and while I can change the output of the filename using the option `mochawesome_filename` I don't see a way to append a timestamp like you would be able to in plain mochawesome.

Is there any way to accomplish this at the moment?

Thanks in advance!

**Comment by fijijavis** [comment]
Hi @ziglef, you are most welcome.  I'm glad you find the reporter useful.

Not sure if this is what you are looking for, but I was able to get a timestamp added to the file name by doing the following:

```
reporterOptions: {
        mochawesome_filename: `my_file_${Date.now()}.json`
    },
```

**Comment by ziglef** [comment]
Yeah, this is what I was looking for! Thanks.

I tried something like this but wasn't able to get it to work, this works nicely!
