### ISSUE TITLE
Make reporter compatible with WebdriverIO v5

### ISSUE THREAD

**Issue by christian-bromann** [fijijavis/wdio-mochawesome-reporter#36]
Hola 👋 

WebdriverIO released v5 around Christmas, see also [this blogpost](https://webdriver.io/blog/2018/12/19/webdriverio-v5-released.html). To make this reporter usable with the new version there are some small adjustments necessary. There are some minor changes that need to be made. You can find a general overview [here](https://webdriver.io/docs/customreporter.html). Most important ones to point out are:

- set `"@wdio/cli": "^5.0.0"` as peerDependency
- let the reporter extend from `@wdio/reporter`
- change the constructor so it calls `super()`
  __Note:__ if your reporter is designed to report to stdout have it the following way:
  ```js
  /**
   * make reporter to write to output stream by default
   */
  options = Object.assign(options, { stdout: true });
  super(options)
  ```
  if your reporter should rather report to a file per default just call:
  ```js
  super(options)
  ```
- all file or stdout messages need to be propagated by `this.write("my log message")`

Feel free to drop by the [`webdriverio/v5`](https://gitter.im/webdriverio/v5) support channel in case you need support.

Thanks so much for contributing to the WebdriverIO community. We really appreciate it 🙏 !

**Comment by christian-bromann** [comment]
Any updates?

**Comment by christian-bromann** [comment]
Any updates?

**Comment by fijijavis** [comment]
@christian-bromann Almost done. I've run across an issue I'm hoping you can help address.  

In v4 as part of the test result we could see a list of the wdio commands that were executed for a test under an ```output``` key.  This reporter uses that info to determine if any screenshots were captured during test execution.  If there were screenshots, then we could have them embedded directly in the HTML report.

With v5, it appears that ```output``` key is no longer available.  Was that purposefully removed?  Does this even make sense?

**Comment by christian-bromann** [comment]
@fijijavis you should be able to use the `beforeCommand` and `afterCommand` methods to track the commands that are being called during the test.

**Comment by fijijavis** [comment]
@christian-bromann Somehow I completely missed those 🤦‍♂️.  Thanks
