### ISSUE TITLE
nested describe/context

### ISSUE THREAD

**Issue by danielyoun82** [fijijavis/wdio-mochawesome-reporter#4]
Hi,

I just noticed that nested describe/context is not supported. If I have example below it out puts json for **suite2** and **test** only. Is there any plan to add ability for nested describe/context? It will be great if that can be done.
`
describe('suite1', function(){
    context('suite2', function(){
        it('test', function(){
        });
    });
});
`
Anyway awesome work! 👍

**Comment by fijijavis** [comment]
@danielyoun82 I'll have to check it out.  I've never considered using ```context``` so I need to see how WDIO treats it from a ```baseReporter``` perspective

**Comment by danielyoun82** [comment]
thanks. I believe it acts the same as describe, so parent (describe in this case) was omitted in the result
