### ISSUE TITLE
Allow consolidated json report to be renamed

### ISSUE THREAD

**Issue by arcmorales** [fijijavis/wdio-mochawesome-reporter#41]
Hello 👋 

First of all, thanks for the upgrade to make `wdio-mochawesome-reporter` compatible with webdriverio v5!

I was trying to consolidate the json reports generated by each test spec and managed to do so via the `mergeResults` utility function. However, I need to have unique filename for the merged files. My use case would be iOS and Android (appium) tests would be running concurrently and I need separate reports for each. 

Is it possible to have a parameter that would accept a filename?

Cheers!

**Comment by fijijavis** [comment]
@arcmorales Glad you are finding this useful.  Yeah, I think having this option makes sense.  I have a full day today but will check our your MR this evening (US Pacific Time).
