### ISSUE TITLE
mergeResults: Error in onCompleteHook: Error: ENOTDIR: not a directory

### ISSUE THREAD

**Issue by fertavora** [fijijavis/wdio-mochawesome-reporter#45]
Hi All!

I am using `wdio-mochawesome-reporter` in the `onComplete` hook.
```
const mergeResults = require('wdio-mochawesome-reporter/mergeResults');
exports.config = {
...
onComplete: function(exitCode, config, capabilities, results) {
        return mergeResults();
    }
};
```
In my `package.json` file I have a script:
```
"scripts": {
    "test": "wdio wdio.conf.js"
  }
```
So when I run `npm test` I got this error:
`ERROR @wdio/cli:utils: Error in onCompleteHook: Error: ENOTDIR: not a directory, scandir 'wdio.conf.js'`

Looks like the `dir` param is not properly passed.
Am I doing something wrong?
Versions I am using:
```
    "@wdio/cli": "^5.10.9",
    "@wdio/local-runner": "^5.10.9",
    "@wdio/mocha-framework": "^5.10.8",
    "@wdio/selenium-standalone-service": "^5.9.3",
    "@wdio/spec-reporter": "^5.9.3",
    "@wdio/sync": "^5.10.8",
    "wdio-mochawesome-reporter": "^3.1.0"
```

Thanks!

**Comment by fijijavis** [comment]
@fertavora Just published a new version `3.2.0` that makes it possible to do what you are trying.  Checkout the README for an example
