### ISSUE TITLE
addContext not worked

### ISSUE THREAD

**Issue by ForeverSc** [fijijavis/wdio-mochawesome-reporter#50]
I use `addContext` from `mochawesome/addContext`:
```js
const addContext = require('mochawesome/addContext')

describe('suite', function() {
  it('test', function() {
    driver.pause(5000)
    // not work
    addContext(this, { 
      title: 'title',
      value: 'value'
    })
  })
})
```
but i found it doesn't work.

According to this line:  [src/index.js#L49](https://github.com/fijijavis/wdio-mochawesome-reporter/blob/master/src/index.js#L49)
`this.currTest.context = JSON.stringify(this.currTest.context)`
Only `this.currTest.context` will be output,  other `addContext` in spec file not worked.

So, is there any way to addContext?

**Comment by fijijavis** [comment]
published new version 4.0.0
