### ISSUE TITLE
More generally, allow any use of addContext

### ISSUE THREAD

**Issue by snoblenet** [fijijavis/wdio-mochawesome-reporter#9]
It appears that the workaround designed to allow saving screenshots wipes `test.context` clean so all other context added through `addContext` will vanish?

https://github.com/fijijavis/wdio-mochawesome-reporter/blob/master/lib/reporter.js#L232

**Comment by snoblenet** [comment]
FYI: https://github.com/webdriverio/wdio-mocha-framework/issues/114

**Comment by snoblenet** [comment]
With my branch:

https://github.com/webdriverio/wdio-mocha-framework/pull/115

You can see context in `wdio-mochawesome-reporter` if you add the following:

```
 _this.on('test:end', function (test) { console.log("Context in reporter", JSON.stringify(test.context, null, 2)); });
```

Right here:

https://github.com/fijijavis/wdio-mochawesome-reporter/blob/master/lib/reporter.js#L26

From there it's just a matter of working out how you want to send it to the report.

Cheers!

**Comment by fijijavis** [comment]
@snoblenet Thanks for the update.  Once the PR for update wdio-mocha-framework is approved and a new version is published this should be do-able pretty easily.

**Comment by snoblenet** [comment]
Great. Thanks. You could also just checkout my branch in the meantime if you had the time to make a start.

**Comment by snoblenet** [comment]
The change has been merged: https://github.com/webdriverio/wdio-mocha-framework/pull/115#event-1380537914

**Comment by snoblenet** [comment]
A patch has been released: https://github.com/webdriverio/wdio-mocha-framework/issues/114#issuecomment-350588365

**Comment by fijijavis** [comment]
Cool.  I’ll work on an update first thing in the morning

**Comment by fijijavis** [comment]
@snoblenet Here's an update.... 

I included ```mochawesome``` as a dependency so that I could use the ```addContext``` function. 

```js
const addContext = require('mochawesome/addContext')
suite('Suite 1',function(){
    test('Sample Test 1',function(){
        addContext(this,"This is a test")
        browser.url('/')
    })
})
```
Good News:   I am able to see context being added to the message being emitted from ```wdio-mocha-framework```

```
{ 
  type: 'test:pass',
  title: 'Sample Test 1',
  parent: 'Suite 1',
  fullTitle: 'Suite 1 Sample Test 1',
  pending: false,
  file: '/Users/jd10778/repos/internal/wdio-best-practice/tests/1.spec.js',
  context: 'This is a test' 
}
```

Bad News:  The WDIO ```BaseReporter``` (used by custom reporters) does not have the context information.  AFAICT, it looks like WDIO  ```ReporterStats``` also needs a MR to add context so that it will be exposed through ```BaseReporter```.

**Comment by snoblenet** [comment]
Is there a branch I can check out to see what PRs we might need to raise on Webdriver.io?

**Comment by fijijavis** [comment]
@snoblenet Not yet.  I have a dummy project where I bumped the version of ```wdio-mocha-framework``` and have the latest ```wdio-mochawesome-reporter```.  I was not seeing context pass through so I started adding ```console.log``` messages to different files in my ```node_modules``` to debug

**Comment by snoblenet** [comment]
Any updates? I don't think the current WIP branch is available for me play with? I'm keen to get started early in case I have to submit a patch to the maintainers of Webdriver.io itself, which may create further details.

**Comment by fijijavis** [comment]
@snoblenet Submitted [PR 2581](https://github.com/webdriverio/webdriverio/pull/2518) in the core WDIO project.  Once this is implemented (and released) we will be able to pull ```context``` into the wdio-mochawesome-reporter

**Comment by snoblenet** [comment]
Looks like there is a linting error? https://travis-ci.org/webdriverio/webdriverio/jobs/316901890

**Comment by snoblenet** [comment]
FYI: https://gitter.im/webdriverio/webdriverio?at=5a38faf05355812e57f2f983

**Comment by snoblenet** [comment]
I see it has been released: https://github.com/webdriverio/webdriverio/blob/master/lib/utils/ReporterStats.js#L343

Any updates from your end? Cheers. And happy new year.

**Comment by fijijavis** [comment]
@snoblenet I should have time to work on this either today or tomorrow.

**Comment by snoblenet** [comment]
Is there a WIP branch that you'd like me to pull and continue work on?

**Comment by snoblenet** [comment]
I've forked the project and will create my own branch designed to address the above issues. https://github.com/snoblenet/wdio-mochawesome-reporter Unless you have a branch that is ready to merge or ready for me to pull and continue working on?

**Comment by fijijavis** [comment]
@snoblenet I did start working on this locally but haven’t gotten very far due to other priorities.  If you want to work on this and submit a PR that would be awesome

**Comment by snoblenet** [comment]
OK no worries. Did you want to push up your incomplete so I can check it for inspiration?

**Comment by snoblenet** [comment]
Should I be removing the "manual screenshot" functionality as part of this PR?

I ask in part because "include manual screenshots as part of context" is the only test that is failing for me when I run the test suite.

The test is saving a screenshot to `/screenshots`, but with a name like `ERROR_phantomjs_...` not `sample.png`.

**Comment by snoblenet** [comment]
The error was because the test was expecting `contextData[0].value` to be a relative path, while the package is returning an absolute value. I've fixed it as party of my branch like this:
```
expect(contextData[0].value.match(/[^\/]*\/[^\/]*$/)[0]).to.equal("screenshots/sample.png")
```

**Comment by fijijavis** [comment]
For now I think we should leave it as an option.   I like having the ability to set it in one place for all screenshots.  

Sorry about the missed failing test.  After your PR I’m planning on doing some refactoring so we can have smaller units of code to test.

Thanks again for picking this up.

**Comment by snoblenet** [comment]
Here's the PR: https://github.com/fijijavis/wdio-mochawesome-reporter/pull/21

All checks are passing. Good to go?

**Comment by fijijavis** [comment]
New version 1.2.0 published to npm this morning.
